### https://api.slack.com/apps/A09CLR5FS1E/incoming-webhooks?success=1

###

POST localhost:8080/notifications
Content-Type: application/json

{
    "Type": "Info",
    "Name": "Quota Exceeded",
    "Description": "Compute Quota exceeded"
}

###

POST localhost:8080/notifications
Content-Type: application/json

{
  "Type": "Warning",
  "Name": "Backup Failure",
  "Description": "The backup failed due to a database problem"
}